# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  name: 'Default'
workspace:
    clean: all # what to clean up before the job runs

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $ROOT = (Get-Item -Path ".\").FullName
      $URI = $env:GCF_PATH
      $URI = "$($URI)GenerateNetlinxCompileCfg?"
      $URI = "$($URI)root=$($ROOT)"
      $URI = "$($URI)&logfile=compile.log"
      $URI = "$($URI)&logconsole=false"
      
      # Fetching compile.cfg
      $R = Invoke-WebRequest -Uri $URI -Method POST -InFile ".\netlinx-global-code.apw" -OutFile ".\compile.cfg" -PassThru -UseBasicParsing
      
      # Output to Console
      Get-Content -Path ".\compile.cfg"
      
      # Exit wtith Compiler Exit Code
      IF($R.StatusCode -ne 200){
          Exit 1
      }
  displayName: 'Fetching the compiler config'
  
- task: PowerShell@2
  inputs:    
    filePath: '.\getReport.ps1'
  displayName: 'Getting Compile Report'
  condition: always()

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Packing up the project'
