# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  name: 'Default'

steps:
- task: PowerShell@2
  inputs:    
    filePath: '.\getConfig.ps1'
  displayName: 'Fetching the compiler config'

- task: PowerShell@2
  inputs:    
    filePath: '.\runCompile.ps1'
  displayName: 'Compiling the Project'

- task: PowerShell@2
  inputs:    
    filePath: '.\getReport.ps1'
  displayName: 'Getting Compile Report'
  condition: always()

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Packing up the project'
