# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- azurepipeline

pool:
  name: 'Default'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$ROOT = (Get-Item -Path ".\").FullName
      
      $URI = "https://us-central1-soloworkslondon.cloudfunctions.net/GenerateNetlinxCompileCfg?"
      $URI = "$($URI)root=$($ROOT)"
      $URI = "$($URI)&logfile=compile.log"
      $URI = "$($URI)&logconsole=true"
      
      $R = Invoke-WebRequest -Uri $URI -Method POST -InFile ".\netlinx-global-code.apw" -OutFile ".\compile.cfg"
      
      Start-Process -FilePath ''C:\Program Files (x86)\Common Files\AMXShare\COM\NLRC.exe'' -ArgumentList  "-CFG""$($ROOT)\compile.cfg""" -NoNewWindow'
  displayName: 'Compiling the Project'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Packing up the project'
